using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: InternalsVisibleTo("Syncfusion.Maui.Charts")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.TabView")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Sliders")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.SignaturePad")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Scheduler")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Calendar")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.DataGrid")]
[assembly: InternalsVisibleTo("SampleBrowser.Maui.Core")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.ListView")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Maps")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Barcode")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Gauges")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.ProgressBar")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Rating")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Inputs")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.DataForm")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Backdrop")]
[assembly: InternalsVisibleTo("Syncfusion.Maui.Popup")]
[assembly: AssemblyCompany("Syncfusion Inc")]
[assembly: AssemblyConfiguration("Release-Xml")]
[assembly: AssemblyCopyright("Copyright 2001 - 2023 Syncfusion Inc.")]
[assembly: AssemblyDescription("This package contains common classes and interfaces that are used in other Syncfusion MAUI controls.")]
[assembly: AssemblyFileVersion("20.4600.0.52")]
[assembly: AssemblyInformationalVersion("20.4600.0.52")]
[assembly: AssemblyProduct("Syncfusion.Maui.Core")]
[assembly: AssemblyTitle("Syncfusion.Maui.Core (LR)")]
[assembly: TargetPlatform("Windows10.0.19041.0")]
[assembly: SupportedOSPlatform("Windows10.0.18362.0")]
[assembly: AssemblyVersion("20.4600.0.52")]
